name: CodeFixit Check

on:
  push:
    paths: ["src/**", "rules/**"]
  pull_request:
    paths: ["src/**", "rules/**"]

jobs:
  codefixit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run CodeFixit dry-run
      run: |
        python cfm.py dry-run --lang cpp --rule qt5to6 --path ./src --diff --report json
